"""MalteseParagraph: thin SynthTIGER-style wrapper for paragraph rendering.

Renders cropped paragraph images from corpus text and emits
(PIL.Image, label_str, label_parts, metadata) tuples.

label_parts is the per-line label list. label_str is the newline-joined view
(`"\n".join(label_parts)`); U+00AD is preserved across that boundary so the
joiner can recover the unsplit word. To get the gold paragraph (single line),
strip U+00AD and collapse newlines/whitespace.

Contract:
- Labels carry only two dash characters: U+002D ("-") and U+2014 ("—").
  En-dash U+2013 is an image-only glyph. The renderer may draw it in a
  fraction of images as a visual-to-canonical signal, but the emitted label
  always normalises U+2013 to U+2014.
- Structural article prefixes (`il-`, `is-`, `id-`, `it-`, `l-`, `fis-`) are
  injected at a configurable rate (default 0.08 lines) when they are not
  already present.
- Hyphenation at line end is generated at `hyphenation_rate` (default 0.06).
  When triggered, the **printed** image breaks the word at the line edge with
  a visible hyphen, but the **label** keeps the word whole and marks the join
  point with a soft-hyphen marker.

Soft-hyphen marker convention: U+00AD (SOFT HYPHEN) is inserted into the label
at the join point. The joiner test set is auto-generated by stripping U+00AD
from the label string. The renderer never draws U+00AD; it only appears in
labels for joiner training.

Layout knobs: font size 8-14pt at 300 dpi, line spacing 1.0-1.6, justification
on/off, leading dashes (` - bullet`) at low rate.

SynthTIGER compatibility: when the upstream `synthtiger` package is importable
and `cfg.use_synthtiger` is True, swap `_render_with_pil` for the SynthTIGER
multiline template. Until then, the PIL path keeps the smoke test self-contained.
"""
from __future__ import annotations

import random
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Iterable, Iterator, List, Optional, Tuple

from PIL import Image, ImageDraw, ImageFont

from .font_loader import FontFace, FontSampler


SOFT_HYPHEN = "­"
EN_DASH = "–"
EM_DASH = "—"

ARTICLE_PREFIXES = ("il-", "is-", "id-", "it-", "l-", "fis-")

# Maltese article-clitic prefixes recognised by the joiner denylist (lowercased).
# Used by the G-case detector to distinguish structural hyphens from compound
# hyphens. Source: malti.line_joiner.Data.get_tokens_with_dash_end().
_STRUCTURAL_CLITICS = frozenset({
    "il-", "is-", "id-", "it-", "in-", "ir-", "iż-", "iz-", "ix-", "iċ-",
    "tal-", "tas-", "tat-", "tad-", "tar-", "tan-", "tax-", "taċ-", "taż-",
    "tah-", "tagħ-",
    "mal-", "mas-", "mat-", "mad-", "mar-", "man-", "max-", "maċ-", "maż-",
    "bil-", "bis-", "bit-", "bid-", "bir-", "bin-", "bix-", "biċ-", "biż-",
    "fil-", "fis-", "fit-", "fid-", "fir-", "fin-", "fix-", "fiċ-", "fiż-",
    "għal-", "għall-", "għas-", "għat-", "għad-", "għar-", "għan-", "għax-",
    "lil-", "lill-", "lis-", "lit-", "lid-", "lir-", "lin-", "lix-", "liċ-", "liż-",
    "sal-", "sas-", "sat-", "sad-", "sar-", "san-", "sax-", "saċ-", "saż-",
    "l-", "s-", "t-", "d-", "r-", "n-", "x-", "ċ-", "ż-",
})


class HyphenKind(str, Enum):
    NONE = "none"
    SOFT = "soft"            # renderer line-break artefact, joiner drops the hyphen
    STRUCTURAL = "structural"  # article-clitic (il-, tas-, ...), joiner keeps it
    COMPOUND = "compound"    # open-class compound (Marie-Louise), joiner keeps hyphen, drops space


def _classify_trailing_hyphen(line: str) -> HyphenKind:
    """Classify the hyphen at the end of `line`, if any. Used at wrap points.

    A line that ends with `-` either carries (a) a soft-hyphen rendered as
    `head-`, (b) a structural clitic such as `il-`, or (c) an internal
    compound hyphen such as `Marie-` where the wrap landed on the dash.
    Distinguishing (b) from (c) is the G-case fix.
    """
    s = line.rstrip()
    if not s.endswith("-"):
        return HyphenKind.NONE
    tail = s.rsplit(" ", 1)[-1]
    if tail.lower() in _STRUCTURAL_CLITICS:
        return HyphenKind.STRUCTURAL
    if "-" in tail[:-1]:
        return HyphenKind.COMPOUND
    if len(tail) <= 4 and tail.lower().endswith("-"):
        return HyphenKind.STRUCTURAL if tail.lower() in _STRUCTURAL_CLITICS else HyphenKind.COMPOUND
    return HyphenKind.COMPOUND


@dataclass
class LayoutConfig:
    dpi: int = 300
    font_pt_lo: int = 8
    font_pt_hi: int = 14
    line_spacing_lo: float = 1.0
    line_spacing_hi: float = 1.6
    paragraph_width_lo: int = 400
    paragraph_width_hi: int = 1200
    pad_x: int = 24
    pad_y: int = 18
    justify_p: float = 0.45
    leading_bullet_p: float = 0.10
    hyphenation_rate: float = 0.06
    article_inject_rate: float = 0.08
    dash_substitute_p: float = 0.05
    # Image-only: fraction of em-dash-bearing printed lines redrawn with an
    # en-dash glyph. Labels keep U+2014 regardless.
    en_dash_image_p: float = 0.30
    # Max lines per paragraph. 0 = no cap. Used by v1 shard generator.
    max_lines: int = 0


@dataclass
class Metadata:
    font_family: str
    font_bucket: str
    font_pt: int
    line_spacing: float
    width_px: int
    height_px: int
    justified: bool
    leading_bullet: bool
    n_lines: int
    n_soft_hyphens: int
    has_article_prefix: bool
    has_unicode_dash: bool
    line_bboxes: List[Tuple[int, int, int, int]] = field(default_factory=list)
    lang: Optional[str] = None
    extras: dict = field(default_factory=dict)
    # Per-line trailing-hyphen classification. len == n_lines. Defaults to NONE
    # for lines that do not end on a hyphen. Added 2026-05-13; the
    # field is additive, so older shards that did not write it will deserialise
    # with an empty list and downstream code must treat missing as NONE.
    hyphen_kinds: List[HyphenKind] = field(default_factory=list)


def _pt_to_px(pt: int, dpi: int) -> int:
    return max(6, int(round(pt * dpi / 72)))


def _maybe_inject_article(text: str, rate: float, rng: random.Random) -> str:
    if rate <= 0 or rng.random() >= rate:
        return text
    if any(p in text.lower() for p in ARTICLE_PREFIXES):
        return text
    parts = text.split(" ", 1)
    if len(parts) < 2:
        return text
    prefix = rng.choice(ARTICLE_PREFIXES)
    parts[1] = prefix + parts[1]
    return " ".join(parts)


def _maybe_substitute_dash(text: str, p: float, rng: random.Random) -> str:
    """Canonical-label dash substitution. The gold inventory has only "-" and
    "—", so the only substitution we make in the label is " - " -> " — ".
    En-dash is never emitted into the label; see _imagewise_en_dash."""
    if p <= 0 or " - " not in text:
        return text
    if rng.random() < p:
        return text.replace(" - ", f" {EM_DASH} ", 1)
    return text


def _imagewise_en_dash(printed: List[str], p: float, rng: random.Random) -> List[str]:
    """Image-only glyph swap: render a fraction of em-dashes as en-dashes so the
    model learns the visual-to-canonical mapping U+2013 -> U+2014. Applies to the
    printed lines only; labels keep U+2014."""
    if p <= 0:
        return printed
    out: List[str] = []
    for ln in printed:
        if EM_DASH in ln and rng.random() < p:
            out.append(ln.replace(EM_DASH, EN_DASH))
        else:
            out.append(ln)
    return out


def _wrap_to_lines(
    text: str,
    font: ImageFont.FreeTypeFont,
    max_width_px: int,
    draw: ImageDraw.ImageDraw,
) -> List[str]:
    """Greedy word-wrap. When a wrap would land *after* an internal hyphen
    of an open-class compound (e.g. `Marie-Louise`), the wrap point is
    shifted to break *before* the hyphen so the suffix line starts with
    `-Louise`. The structural-clitic forms (`il-`, `tas-`, ...) are left
    untouched - those should still wrap after the dash.
    """
    words = text.split()
    lines: List[str] = []
    cur: List[str] = []
    for w in words:
        trial = " ".join(cur + [w])
        if draw.textlength(trial, font=font) <= max_width_px or not cur:
            cur.append(w)
        else:
            last = cur[-1]
            if "-" in last:
                idx = last.rfind("-")
                prefix = last[: idx + 1].lower()
                head, tail = last[:idx], last[idx:]
                if (
                    head
                    and tail
                    and len(tail) >= 2
                    and prefix not in _STRUCTURAL_CLITICS
                ):
                    cur[-1] = head
                    lines.append(" ".join(cur))
                    cur = [tail, w]
                    continue
            lines.append(" ".join(cur))
            cur = [w]
    if cur:
        lines.append(" ".join(cur))
    return lines


def _apply_hyphenation(
    lines: List[str],
    rate: float,
    rng: random.Random,
) -> Tuple[List[str], List[str], int, List[HyphenKind]]:
    """Return (printed_lines, label_lines, n_soft_hyphens, hyphen_kinds).

    printed_lines: what is drawn; trailing word gets split with a visible "-".
    label_lines: a single joined label with U+00AD at the soft-hyphen point.
    hyphen_kinds: one entry per printed line classifying its trailing hyphen.
    """
    n_soft = 0
    out_print: List[str] = []
    out_label_parts: List[str] = []
    kinds: List[HyphenKind] = []
    i = 0
    while i < len(lines):
        ln = lines[i]
        has_next = i + 1 < len(lines)
        words = ln.split()
        if has_next and rate > 0 and rng.random() < rate and len(words) >= 2 and len(words[-1]) >= 6:
            last = words[-1]
            cut = max(2, len(last) // 2)
            head, tail = last[:cut], last[cut:]
            printed_line = " ".join(words[:-1] + [head + "-"])
            next_line_words = lines[i + 1].split()
            next_printed = " ".join([tail] + next_line_words)
            out_print.append(printed_line)
            out_print.append(next_printed)
            label_chunk = " ".join(words[:-1] + [head + SOFT_HYPHEN + tail])
            out_label_parts.append(label_chunk)
            out_label_parts.append(" ".join(next_line_words))
            kinds.append(HyphenKind.SOFT)
            kinds.append(HyphenKind.NONE)
            n_soft += 1
            i += 2
        else:
            out_print.append(ln)
            out_label_parts.append(ln)
            if has_next:
                kind = _classify_trailing_hyphen(ln)
                if kind == HyphenKind.NONE and lines[i + 1].lstrip().startswith("-"):
                    kind = HyphenKind.COMPOUND
                kinds.append(kind)
            else:
                kinds.append(HyphenKind.NONE)
            i += 1
    return out_print, out_label_parts, n_soft, kinds


def _render_with_pil(
    printed_lines: List[str],
    font: ImageFont.FreeTypeFont,
    line_spacing: float,
    pad_x: int,
    pad_y: int,
    width_px: int,
    justify: bool,
) -> Tuple[Image.Image, List[Tuple[int, int, int, int]]]:
    ascent, descent = font.getmetrics()
    line_h = int(round((ascent + descent) * line_spacing))
    height = pad_y * 2 + line_h * max(1, len(printed_lines))
    img = Image.new("RGB", (width_px, height), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)
    y = pad_y
    bboxes: List[Tuple[int, int, int, int]] = []
    for idx, ln in enumerate(printed_lines):
        if justify and idx < len(printed_lines) - 1 and " " in ln:
            _draw_justified(draw, ln, font, pad_x, y, width_px - 2 * pad_x)
        else:
            draw.text((pad_x, y), ln, font=font, fill=(0, 0, 0))
        bboxes.append((0, y, width_px, y + line_h))
        y += line_h
    return img, bboxes


def _draw_justified(draw, line: str, font, x: int, y: int, target_w: int) -> None:
    words = line.split(" ")
    if len(words) <= 1:
        draw.text((x, y), line, font=font, fill=(0, 0, 0))
        return
    word_widths = [draw.textlength(w, font=font) for w in words]
    base_space = draw.textlength(" ", font=font)
    extra = target_w - sum(word_widths) - base_space * (len(words) - 1)
    if extra <= 0:
        draw.text((x, y), line, font=font, fill=(0, 0, 0))
        return
    per_gap = extra / (len(words) - 1)
    cx = x
    for i, w in enumerate(words):
        draw.text((cx, y), w, font=font, fill=(0, 0, 0))
        cx += word_widths[i] + base_space + per_gap


class MalteseParagraph:
    def __init__(
        self,
        font_sampler: FontSampler,
        layout: Optional[LayoutConfig] = None,
        rng: Optional[random.Random] = None,
    ) -> None:
        self.fonts = font_sampler
        self.layout = layout or LayoutConfig()
        self.rng = rng or random.Random()

    def __call__(self, corpus_iter: Iterable[dict]) -> Iterator[Tuple[Image.Image, str, List[str], Metadata]]:
        for row in corpus_iter:
            yield self.render_one(row)

    def render_one(self, row: dict) -> Tuple[Image.Image, str, List[str], Metadata]:
        text = row["text"]
        text = _maybe_inject_article(text, self.layout.article_inject_rate, self.rng)
        text = _maybe_substitute_dash(text, self.layout.dash_substitute_p, self.rng)

        leading_bullet = self.rng.random() < self.layout.leading_bullet_p
        if leading_bullet:
            text = " - " + text

        font_face = self.fonts.sample()
        pt = self.rng.randint(self.layout.font_pt_lo, self.layout.font_pt_hi)
        px = _pt_to_px(pt, self.layout.dpi)
        font = ImageFont.truetype(str(font_face.path), px)

        width_px = self.rng.randint(self.layout.paragraph_width_lo, self.layout.paragraph_width_hi)
        spacing = self.rng.uniform(self.layout.line_spacing_lo, self.layout.line_spacing_hi)
        justify = self.rng.random() < self.layout.justify_p

        scratch = Image.new("RGB", (10, 10))
        d = ImageDraw.Draw(scratch)
        max_text_w = width_px - 2 * self.layout.pad_x
        lines = _wrap_to_lines(text, font, max_text_w, d)
        printed, label_parts, n_soft, hyphen_kinds = _apply_hyphenation(
            lines, self.layout.hyphenation_rate, self.rng
        )
        label_parts = [re.sub(r"[ \t]+", " ", p).strip(" \t") for p in label_parts]
        label = "\n".join(label_parts)

        printed = _imagewise_en_dash(printed, self.layout.en_dash_image_p, self.rng)

        img, bboxes = _render_with_pil(
            printed, font, spacing, self.layout.pad_x, self.layout.pad_y, width_px, justify
        )

        meta = Metadata(
            font_family=font_face.family,
            font_bucket=font_face.bucket,
            font_pt=pt,
            line_spacing=spacing,
            width_px=width_px,
            height_px=img.height,
            justified=justify,
            leading_bullet=leading_bullet,
            n_lines=len(printed),
            n_soft_hyphens=n_soft,
            has_article_prefix=any(p in label.lower() for p in ARTICLE_PREFIXES),
            has_unicode_dash=EM_DASH in label,
            line_bboxes=bboxes,
            lang=row.get("lang"),
            hyphen_kinds=hyphen_kinds,
        )
        return img, label, label_parts, meta
